### ISSUE TITLE
please remember to increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [Wohlstand/ADLMIDI-Player-Java#4]
All APKs attached to `releases/` have `versionCode:1`. That's not proper: Android uses that variable to tell updates (so currently there are none). Could you please (starting with the next release) increase that number? Must just be numeric and larger than the previous one. You can use that as "number of releases", or whatever you like – as long as it's bigger than that from the previous version :wink:

Thanks!

**Comment by Wohlstand** [comment]
Oh, thanks for note that it's the counter of releases, but not a "major version" number :fox_face:
Will update it in next time ;3

**Comment by IzzySoft** [comment]
Thanks, @Wohlstand – and yes, the easiest use is "release counter". Some projects use it like "major*10000 + minor*100 + patch", to e.g. map "v2.1.3" to "20103". Works as well, as the resulting integer again is always bigger than the previous.

Background of my request: your app is in [my F-Droid compatible repository](https://apt.izzysoft.de/fdroid/index/apk/ru.wohlsoft.adlmidiplayer). For users to be notified of updates … well, see above :wink:

PS: With the versionCode fixed, your app seems to meet all requirements to be listed at the [official F-Droid repo](https://f-droid.org/). Would you like it to appear there? Just let me know, and I gladly assist you (disclosure: I'm one of the maintainers there).

**Comment by Wohlstand** [comment]
I see, anyway even this app isn't so perfect player that lacks playlists and things, and able to play only one song looped, but working example with real time tuning support that I use by myself to unit-test the libADLMIDI itself while I'm in the path :fox_face: :smile: 

Gonna to apply recent fixes now...

**Comment by Wohlstand** [comment]
Okay, I have fixed this just now! :fox_face: :+1: 
Also, I have updated the libADLMIDI here, and, I gonna to upload my recent releases now

**Comment by Wohlstand** [comment]
I also have updated similar OPNMIDI player app that does use of libOPNMIDI library which is based on YM2612 (OPN2) chip while this on YMF262 :wink:

**Comment by IzzySoft** [comment]
Cool! My updater picked v1.4.2 today – and will fetch future updates as soon as there's a matching tag with APK attached.

As for the official repo: Take your time. Ping me if you want your app listed, and I'll gladly assist you in the process of bringing it there.

**Comment by Wohlstand** [comment]
Thanks! :fox_face: :smiley: 
Also, @IzzySoft , can you also add my [OPNMIDI Player](https://github.com/Wohlstand/OPNMIDI-Player-Java) too? It's similar to this, but it using different chip to OPL3: it does use of OPN2 of libOPNMIDI that is here: https://github.com/Wohlstand/libOPNMIDI

**Comment by Wohlstand** [comment]
Anyway, as you confirmed the thing is done, I'll close this! :wink:

**Comment by IzzySoft** [comment]
Yupp! And done adding your other app. Will show up after the next sync (i.e. latest tomorrow evening, unless I trigger one manually – but I did that 3 times already today, so I don't want to confuse the #fdroid IRC channel with too many announcements :rofl:)

Thanks!

**Comment by IzzySoft** [comment]
Just a keep-alive (as this issue is closed; maybe we should open a separate issue for this) for bringing this app (or both apps) to the official repo :wink:
