### ISSUE TITLE
Application sometimes may lag or dead-freeze in any random moment

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/ADLMIDI-Player-Java#5]
While playing music and trying various actions, it may freeze in random moment, offtenly, on attempt to open another song or switch the bank.

**Comment by freq-mod** [comment]
I didn't experience any freeze yet, bu I noticed often that when screen goes dark when song is playing, it starts to lag heavily.
The easiest workaround would be do forbid device to enter sleep  during playback I guess...

**Comment by Wohlstand** [comment]
About sudden freeze, I may guess it's the possible dead lock that may happen in `applySetup()` call

**Comment by Wohlstand** [comment]
I guess I resolved this mess a while ago by upgrading the whole background services thing.
