### ISSUE TITLE
Download for recent versions missing

### ISSUE THREAD

**Issue by IzzySoft** [Wohlstand/ADLMIDI-Player-Java#7]
Is v1.4.4 really the latest release? According to the commit history, version has been bumped a few times up to its current 1.5.0.5. Will you provide those APKs as well, ideally with [`releases/`](https://github.com/Wohlstand/ADLMIDI-Player-Java/releases), as the Readme suggests? Thanks!

**Comment by Wohlstand** [comment]
Yes, it's the latest STABLE release. I began the big work recently to bypass updates of my main part - the libADLMIDI library. Also, I going to rework the internality of an audio service that works not good. I releasing some betas at PlayMarket, but thanks, I must release my betas also here as raw APKs. The current state of 1.5.0.5 does give a set of new features, however, a logic to work of audio service isn't good, I must rework the way to communicate the frontend and the daemon to change settings on the fly and don't start the service when nothing to play.

**Comment by IzzySoft** [comment]
Thanks for the fast response! Good to know the background. And nice to see you using the Play folks as testers, giving the honest Play-avoiders only stable things :rofl: Maybe point that out in the Readme, to avoid confusion, until there's a stable release again? You could also release the test versions, marking them "pre-release". Then it's everyone's choice ti chime in with testing or sticking to stable, approved versions.

**Comment by Wohlstand** [comment]
That right, thanks for a note :fox_face:

**Comment by Wohlstand** [comment]
For everyone's convenience, I made the CI via GitHub Actions that just works. So, even if I didn't make any releases, everyone will be able to retrieve the latest auto-built binary at any moment.

**Comment by IzzySoft** [comment]
Thanks! I've told my updater to fetch the pre-releases as well for now (as there was no release for 3 years). From the release notes, it sounds like they are stable enough to be "thrown at the public" :wink:
