### ISSUE TITLE
[Question] Possible iOS version?

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/ADLMIDI-Player-Java#8]
I know what are the nuances of portable Apple devices and iOS SDK, but is it possible this player will get an iOS support in the future? How much of the app would have to be remade?

**Comment by Wohlstand** [comment]
That would be a different player implementation over the library. This player I made is just a simple overlay over my library. 

The work requires:
* macOS
* Xcode
* Any hardware iDevice to verify the actual work

However, publishing the thing requires:
* Apple Developer account that costs $100 per year (7779,5 RUR, 387,64 PLN, for such money I better buy the new 48-ports switch for my ARM claster to replace old dying that I have now)
* Alternatively, publish in Cydia for Jailbroken devices
* Just publish IPS and refer the manual at the tricky RetroArch's manual for that

**Comment by Wohlstand** [comment]
The main answer on the question: technically it's possible, and distrubute it as a source code for the manual build by every user.

**Comment by freq-mod** [comment]
>Apple Developer account that costs nearly 400 PLN per year

:eyes: :eyes: 

>distrubute it as a source code for the manual build by every user.

I doubt it's a sensible approach for a typical end-user. Thanks for the answer and info, nevertheless.
