### ISSUE TITLE
Unable to build (gradle fails)

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/ADLMIDI-Player-Java#9]
During the start of a Gradle Daemon, this happens:

```
FAILURE: Build failed with an exception.

* Where:
Settings file '/home/anon/ADLMIDI-Player-Java/settings.gradle'

* What went wrong:
Could not compile settings file '/home/anon/ADLMIDI-Player-Java/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60
  
  java.lang.IllegalArgumentException: Unsupported class file major version 60
```
at the every single file of this project. Java version is openjdk 16.0.1 2021-04-20

**Comment by Wohlstand** [comment]
The question, did you installed the Android SDK and NDK? Or you do trying to build the thing using the vanilla Java environment?

**Comment by freq-mod** [comment]
the second option, I will try with android sdk...

**Comment by Wohlstand** [comment]
This is fully Android project, and you can't use vanilla Java environment to build this

**Comment by freq-mod** [comment]
Yeah, I managed to build this now. Thanks
